### PR TITLE
Fix reference counting when device connections fail

### PR DESCRIPTION
**Pull request by IngmarStein**
This PR addresses #3 and also bumps Rust and dependencies.

### CODE REVIEW

**Comment by IngmarStein** [comment]
Ping @tiagocoutinho

**Comment by jonasjelonek** [comment]
@IngmarStein 
I just wanted to get into contact with you about that project ... seems like it's dead or at least mostly inactive from the maintainer's side. 
I'm using that app because it fits my environment quite well. My solar inverter is put behind a separate gateway (mostly because I don't trust Huawei calling home) and I need such a proxy because the inverter's Modbus implementation seems to be quite crappy. The gateway is rather low-powered device, but the Modbus proxy runs fine on it and I wanted to keep that as close as possible to the inverter instead of spreading it in my network.

I had a PR until recently which solved some issues for me, and you have that one here too :). Are you still interested in improving that app here or have you switched to an alternative? I refused to do so for several reasons (complexity, other issues, etc.) and would really like to improve it, probably in a fork for now.

**Comment by IngmarStein** [comment]
@jonasjelonek inverters with crappy Modbus implementations seem to be the top reason why this project exists / existed. Maybe try if your problem is solved with this PR. Like others in https://github.com/tiagocoutinho/modbus-proxy/issues/31, I've since moved on: if one device reading from the inverter can re-publish the data in a way that others can consume, it can logically at as a proxy as well. In my case, it's a cloud service, but others made the data available via MQTT. This is not great, but it works. If you could fix this project, I might consider moving back to modbus-proxy, but due to the lack of feedback from the maintainer, I'll not put more work into it.

**Comment by jonasjelonek** [comment]
Thanks for your quick reply. I also thought about using similar alternatives, but decided against it to keep the setup simple in my network. I'll definitely try to fix some issues here, and probably improve other things since I have quite an interest in reviving this and I don't want to use the Python version, even if it was maintained.

**Review by tiagocoutinho — APPROVED** [review]
Thank you for the contribution.

LGTM!

**Comment by tiagocoutinho** [comment]
I'd like to add an apology for the lack of feedback.

**Comment by IngmarStein** [comment]
@tiagocoutinho no worries. Would it be possible to create a new release tag and push a build to Docker Hub so that it's easier to pick up the fix?

@jonasjelonek I might have found another use case for this project in my setup. Were you able to test the build and see whether it fixes the issues you encountered?

**Comment by jonasjelonek** [comment]
@IngmarStein I had the time to test the changes, but in my usecase the issues weren't solved. But that may also be caused be the clients that try to access the Modbus device via the proxy. It seems they very often connect to the proxy but do not terminate the connections leading to a panic and even warning coming from Linux. But this only occurs if the connection to the modbus-proxy is lost for a couple of minutes, e.g. after a nightly reboot of the proxy device.

**Comment by IngmarStein** [comment]
@jonasjelonek it sounds familiar to the things I experienced when I used modbus-proxy (it's been a while, so the details are fuzzy). I think looked at connection lifecycle management because in some cases, clients starting hanging when using the proxy, but not when talking to the modbus server directly.

I stumbled upon https://github.com/XUJiahua/tcp-multiplexer which could also be a simple solution (if extended for the modbus prototcol), but it's old and likely unmaintained.

**Comment by IngmarStein** [comment]
@jonasjelonek if you'd like, you could give https://github.com/IngmarStein/tcp-multiplexer a try.

**Comment by jonasjelonek** [comment]
I will have a look, thanks. At least I can try if that doesn't have the issues I experience with this app here.

**Pull request merged**
